sudo: required
services:
  - docker
before_install:
  # pass encrypted key from travis cli
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install and update kubectl in travis
  - gcloud components update kubectl
  # authenticate to google
  - gcloud auth activate-service-account --key-file service-account.json
