apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # define how the storage option will be used
  accessModes:
    # storage can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      # storage is 2 Gigabytes 
      storage: 2Gi